#!/usr/bin/env bash
set -eu

show_help() {
  printf 'Usage:\n'\
'  %s <mkkey|issue|csr|ca|revoke|mkcnf|selfsign|mkp12> -h\n'\
  "$0"
}

if [ $# -lt 1 ] ; then
  show_help
  exit 1
fi

cmd=$1
shift

this_file="${BASH_SOURCE[0]}"
if ! [ -e "$this_file" ] ; then
  this_file="$(type -p "$this_file")"
fi
if ! [ -e "$this_file" ] ; then
  echo "Failed to resolve file."
  exit 1
fi
if ! [[ "$this_file" =~ ^/ ]] ; then
  this_file="$(pwd)/$this_file"
fi
while [ -h "$this_file" ] ; do
    ls_res="$(ls -ld "$this_file")"
    link_target=$(expr "$ls_res" : '.*-> \(.*\)$')
    if [[ "$link_target" =~ ^/ ]] ; then
      this_file="$link_target"
    else
      this_file="$(dirname "$this_file")/$link_target"
    fi
done
this_dir="$(dirname "$this_file")"

cmd_file="${this_dir}/${cmd}.sh"
if ! [ -f "$cmd_file" ] ; then
  echo "command not exist: $cmd" >&2
  exit 1
fi

"${cmd_file}" "$@"
